### ISSUE TITLE
How can this be used via stack?

### ISSUE THREAD

**Issue by tonyalaribe** [yvan-sraka/cargo-cabal#13]
Hi, I followed the readme tutorial and it worked perfectly. 
But I've unable to reproduce this with stack and always run into the error:

```
rust-interop     > .stack-work/dist/aarch64-osx/ghc-9.8.1/build/librust_interop.a: copyFile: does not exist (No such file or directory)
```

<img width="766" alt="CleanShot 2024-04-11 at 13 48 40@2x" src="https://github.com/yvan-sraka/cargo-cabal/assets/6564482/0083d8e4-cac6-4cc7-bd7a-248e5437ac71">

Following the step steps, except using the stack.yaml to configure `extra-deps` from the parent haskell project, to the other haskell+rust library created according to the tutorial.

Do you have any pointers on what I should do to make this work with stack (no cabal.project file)?

I added the following to the package.yaml (hpack used by stack), and it doesn't solve the errors
```

library:
  extra-lib-dirs:
    - ${pkgroot}/rust-interop/target/debug
  extra-libraries: 
    - rust_interop
  source-dirs: 
    - src
    - rust-interop/src

```
